name: covapt
channels:
  - defaults
  - bccp
dependencies:
  - jupyter
  - python=3.7
  - tqdm
  - matplotlib
  - nbodykit
platforms:  # need to exclude osx-arm64 because of nbodykit
  - linux-64
  - osx-64
