input_dir : "/Users/anniemoore/Documents/spherexVirtual/covariance_code/covapt_mt/data/input_data/impact_studies/"
output_dir : "/Users/anniemoore/Documents/spherexVirtual/covariance_code/covapt_mt/data/output_data/impact_studies/"

# parameters for producing the window function
make_gaussian_window : True
make_ssc_window : False # <- currently not configured for multi-tracer!
make_random_ffts: False
random_file_prefix : random_flipnz_2_0
#random_file_prefix : "boss_data/random0_DR12v5_CMASS_North"
# window_file_prefix : "Wij_"
window_file_prefix : "Wij0_"
fft_mesh_size : 128
# Amount to pad the box size by (multiplicitave)
# OR specify the box size directly
# box_padding : 1.2
box_size : 6000 # Mpc/h
# number of kmodes to sample
# The default used by Jay Wadekar was 25000, which was run on a cluster
kmodes_sampled : 100
num_processes : 1
num_tracers : 1
zbins:
  bin1_lo : 1.0
  bin1_hi : 1.6

h : 0.7
Om0 : 0.31

make_Gaussian_cov : True
# k_array_file : "k_impact.npz"
k_array_file : "k_hybrid_log.npz"
# k_array_file : "lin_karray.npz"
sampling_mode : "log" # "linear" or "log"
# pk_galaxy_file :  "ps_1loop_hubble_true_link_galaxy_ps copy.npy"
# pk_galaxy_file : "ps_1loop_khybridUpdated_galaxy_ps.npy"
pk_galaxy_file : "ps_1loop_hybridLog_galaxy_ps.npy"
# pk_galaxy_file : "ps_1loop_galaxy_ps_1z.npy"
covariance_file : "cov_1_tracer_1_redshift_log.npz"

alpha : [0.01]
# just set to a small number for now, more robust option when we have real randoms
#alpha : [0.07, 0.07]
#alpha : [0.07, 0.406] #, 0.522] 