input_dir : "/home/joeadamo/Research/SPHEREx/covapt_mt/data/input_data/"
output_dir : "/home/joeadamo/Research/SPHEREx/covapt_mt/data/output_data/"

# parameters for producing the window function
make_gaussian_window : False
make_ssc_window : False # <- currently not configured for multi-tracer!
random_file_prefix : "random_emu_test_"
window_file_prefix : "Wij_emu_"
fft_mesh_size : 200
# Amount to pad the box size by (multiplicitave)
box_padding : 1.2
# number of kmodes to sample
# The default used by Jay Wadekar was 25000, which was run on a cluster
kmodes_sampled : 5000
num_processes : 14
num_tracers : 3
zbins:
  bin2_lo : 0.4
  bin2_hi : 0.6

h : 0.7
Om0 : 0.31

make_Gaussian_cov : True
k_array_file : "k_emu_test.npz"
pk_galaxy_file : "ps_emu_test.npy"
covariance_file : "cov_test.npz"
#alpha : None 
n_galaxy : [.000501, 0.00282, 0.00362]