input_dir : "/home/joeadamo/Research/SPHEREx/covapt_mt/data/input_data/"
output_dir : "/home/joeadamo/Research/SPHEREx/covapt_mt/data/output_data/"

# parameters for producing the window function
make_gaussian_window : False
make_ssc_window : False # <- currently not configured for multi-tracer!
random_file_prefix : "random_"
window_file_prefix : "Wij_"
num_processes : 14
fft_mesh_size : 100
# size of the survey in Mpc/h
box_size : 3200
# number of kmodes to sample
# The default used by Jay Wadekar was 25000, which was run on a cluster
kmodes_sampled : 20
num_tracers : 2
zbins:
  bin1_lo : 0.2
  bin1_hi : 0.4
  bin2_lo : 0.4
  bin2_hi : 0.5

h : 0.7
Om0 : 0.3

make_Gaussian_cov : True
k_array_file : "k_test.npz"
pk_galaxy_file : "ps_for_Robin.npy"
covariance_file : "cov_test.npy"
alpha : 1.
n_galaxy : [3.e-4]